twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'form_layout.html.twig'
    exception_controller: App\Controller\ExceptionController::showAction